# Default values for api-authorization.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
 
replicaCount: 2
 
image:
  repository: gcr.io/production-main-268117/api-authorization
  tag: 4.1.1.0
  pullPolicy: IfNotPresent
 
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
 
service:
  type: ClusterIP
  port: 80
 
properties:
  javaOpts: "-Djava.security.egd=file:/dev/./urandom -Dfile.encoding=UTF8 -Dlog4j2.formatMsgNoLookups=True -Xms1536m -Xmx1536m -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError"
  redis:
    connectionType: "CHANGE_HERE" #Example MASTER_SLAVE or CLUSTER (#depends on your redis setup)
    address: "redis://CHANGE_HERE" #Example: "redis://x.x.x.x:6379". Note that port is required
    password: "CHANGE_HERE"
  tokenTarget: "HTTP"
  logstashUrl: "http://CHANGE_HERE/" #Example "http://x.x.x.x" # port default 80
 
autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  averageUtilization: 70
 
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
 
resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 600m
    memory: 640Mi
 
nodeSelector: {}
 
tolerations: []
 
affinity: {}

