# Default values for logstash-federated.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
 
replicaCount: 1
 
image:
  repository: gcr.io/production-main-268117/logstash-federated
  tag: 4.1.2.0
  pullPolicy: IfNotPresent
 
service:
  type: ClusterIP
  port: 80
 
properties:
  customer_id: "CHANGE_HERE"
  sensedia_auth: "CHANGE_HERE"
  #--- IF client in AWS
  apiplatform_proxy_url: "https://integration-aws.sensedia.com"
  #--- If client in GCP
  #apiplatform_proxy_url: "https://integration-production-gcp.sensedia.com"
  apiplatform_connect_timeout: "10"
  apiplatform_retries: "3"
  ls_proxy: ""
  #--- The default value of variable ls_bind_port (bind logstash) is 8080, if necessary, change below:
  #ls_bind_port: ""
 
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  averageUtilization: 70
 
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
 
resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 600m
    memory: 640Mi
    
metrics:
  enabled: false
  imageTag: 5.0.0.0
  containerPort: 9198
  resources:
    limits:
      cpu: 100m
      memory: 200Mi
    requests:
      cpu: 10m
      memory: 20Mi

serviceMonitor:
  # Depends on metrics to be enabled
  enabled: false
  additionalLabels: {}
  path: "/metrics"
  scrapeTimeout: "5s"
  # namespace: "monitoring"
  # scrapeInterval: 30s
  # honorLabels: true
  namespaceSelector: {}
  # Default: scrape .Release.Namespace only
  # To scrape all, use the following:
  # namespaceSelector:
  #   any: true

nodeSelector: {}
 
tolerations: []
 
affinity: {}

