version: '2.4'
services:

  api-gateway:
    env_file: api-gateway.env
    networks:
      - api-platform
    image: gcr.io/production-main-268117/api-gateway:4.3.0.2
    container_name: api-gateway
    cpu_count: 1
    mem_limit: 2048m
    restart: always
    ports:
      - '8080:8080'

networks:
  api-platform:
    name: api-platform

