# Default values for api-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: gcr.io/production-main-268117/api-gateway
  tag: 4.3.0.2
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

properties:
  java_opts: "-Djava.security.egd=file:/dev/./urandom -Dlog4j2.formatMsgNoLookups=True -Dfile.encoding=UTF8 -Xms1536m -Xmx1536m -XX:ParallelGCThreads=1 -XX:ConcGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:+ExitOnOutOfMemoryError -Dtomcat.relaxedQueryChars='[]|{}^&#x5c;&#x60;&quot;&lt;&gt;' -Dtomcat.maxThreads=400"
  redis_token_connectiontype: "CHANGE_HERE"  #Example MASTER_SLAVE or CLUSTER (#depends on your redis setup)
  redis_token_address: "redis://CHANGE_HERE" #Example: "redis://x.x.x.x:6379". Note that port is required 
  redis_token_password: "CHANGE_HERE"
  redis_scenario_connectiontype: "CHANGE_HERE"  #Example MASTER_SLAVE or CLUSTER (#depends on your redis setup)
  redis_scenario_address: "redis://CHANGE_HERE" #Example: "redis://x.x.x.x:6379". Note that port is required
  redis_scenario_password: "CHANGE_HERE"
  redis_cache_connectiontype: "CHANGE_HERE"  #Example MASTER_SLAVE or CLUSTER (#depends on your redis setup)
  redis_cache_address: "redis://CHANGE_HERE" #Example: "redis://x.x.x.x:6379". Note that port is required
  redis_cache_password: "CHANGE_HERE" 
  customer_id: "CHANGE_HERE"
  logstash_url: "http://CHANGE_HERE/" #Example "http://x.x.x.x:80/". Note that the last slash is required
  metric_target: "HTTP"
  apigateway_http_connection_timeoutmillis: 10000
  apigateway_http_socket_timeoutmillis: 10000
  apigateway_label: "federated"
  apigateway_use_cachemanager: "false"
  spring_profiles_active: "federated"

proxy:
  enabled: false
  sensedia_apigateway_proxy_url: "proxy.example.com"
  sensedia_apigateway_proxy_port: 3128
  sensedia_apigateway_proxy_username: ""
  sensedia_apigateway_proxy_password: ""

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  averageUtilization: 70

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: "1"
    memory: 2Gi
  requests:
    cpu: 600m
    memory: 1.5Gi

nodeSelector: {}

tolerations: []

affinity: {}

