#All in one
version: '2.4'
services:
  redis:
    env_file: hybrid.env
    networks:
      - api-platform
    image: redis:5.0.9-alpine
    container_name: redis
    command: redis-server --notify-keyspace-events KEA
    mem_limit: 512m
    volumes:
       - /data/redis-standalone:/data
    ports:
      - "6379:6379"

  logstash-federated:
    env_file: hybrid.env
    networks:
      - api-platform
    image: gcr.io/production-main-268117/logstash-federated:4.1.1.0
    container_name: logstash-federated
    cpu_count: 1
    mem_limit: 1024M
    mem_reservation: 512m
    restart: always
    ports:
      - '9600:9600'
      - '8090:8080'

  agent-authorization:
    env_file: hybrid.env
    networks:
      - api-platform
    depends_on:
      - redis
    image: gcr.io/production-main-268117/agent-authorization:1909.1.1.2
    container_name: agent-authorization
    mem_limit: 512m
    restart: always
    ports:
      - '8092:8092'

  agent-gateway:
    env_file: hybrid.env
    networks:
      - api-platform
    depends_on:
      - redis
    image: gcr.io/production-main-268117/agent-gateway:1909.1.1.1
    container_name: agent-gateway
    mem_limit: 512m
    restart: always
    ports:
      - '8091:8091'

  api-authorization:
    env_file: hybrid.env
    networks:
      - api-platform
    depends_on:
      - agent-authorization
    image: gcr.io/production-main-268117/api-authorization:4.1.1.0
    container_name: api-authorization
    depends_on:
      - redis
    mem_limit: 2048m
    restart: always
    ports:
      - '8084:8084'

  api-gateway:
    env_file: hybrid.env
    networks:
      - api-platform
    depends_on:
      -redis
      - agent-gateway
      - logstash-federated
    image: gcr.io/production-main-268117/api-gateway:4.3.0.2
    container_name: api-gateway
    cpu_count: 1
    mem_limit: 2048m
    restart: always
    ports:
      - '8080:8080'

networks:
  api-platform:
    name: api-platform
